name: Execute and upload SYNOPSYS Coverity Scan

on:
  schedule:
      - cron: '15 4 * * *'

jobs:
  executeCoverityScan:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'eryaf/mk-cross-builder'
      DOCKER_TAG: 'amd64_10'

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
        path: to_build

    - name: Prepare SYNOPSYS Coverity Scan Analysis Tools
      run: |
        wget https://scan.coverity.com/download/cxx/linux64 \
        --post-data "token=${{ secrets.SYNOPSYS_COVERITY_SCAN_TOKEN }}&project=${{ github.repository }}" \
        -O scs_analysis_tool.tgz
        mkdir scs_analysis_tool
        tar zxvf scs_analysis_tool.tgz -C scs_analysis_tool
        cd scs_analysis_tool && cd cov-analysis-linux64-*
        find . -maxdepth 1 -not \( -path "." \) -exec mv {} .. \;
        cd ../..
      working-directory: ./to_build

    - name: Build Machinekit code on AMD64 with Coverity Scan
      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ env.DOCKER_TAG }} -c coverity
      working-directory: ./to_build

    - name: Send report to SYNOPSYS servers
      run: |
        curl --form token=${{ secrets.SYNOPSYS_COVERITY_SCAN_TOKEN }} \
        --form email=${{ secrets.MACHINEKITBOT_EMAIL_ADDRESS }} \
        --form file=@machinekit-hal-coverity.tgz \
        --form version="${{ github.ref }}" \
        --form description="Build from GIT SHA ${{ github.sha }}" \
        https://scan.coverity.com/builds?project=${{ github.repository }}
      working-directory: ./to_build